### ISSUE TITLE
API Key in commit history

### ISSUE THREAD

**Issue by rclarke10** [Hobbits52/ComputerVision#82]
I stumbled across this repo and I noticed on of your commits shows your API key for heroku:

https://github.com/Hobbits52/ComputerVision/commit/feb6122ab21737d260cafacf534a127e543b8ac2

I'd suggest requesting a new API key before the key gets scraped. 

Cheers!

**Comment by anthonypecchillo** [comment]
Thank you for letting me know!  I was under the impression that an encrypted API Key was secure in version control...is this not true?
